name: cp_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  anim_search_bar: ^2.0.3
  any_link_preview: ^3.0.0
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  chips_choice_null_safety: ^2.0.6
  dartz: ^0.10.1
  dropdown_button2: ^2.1.2
  equatable: ^2.0.5
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  flutter_bloc: ^8.1.2
  flutter_email_sender: ^5.2.0
  flutter_local_notifications: ^14.0.0+2
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.1
  get_it: ^7.6.0
  google_nav_bar: ^5.0.6
  graphql_flutter: ^5.1.2
  http: ^0.13.6
  hydrated_bloc: ^9.1.0
  image_picker: ^0.8.7+5
  insta_assets_picker: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.3.2
  photo_view: ^0.14.0
  shared_preferences: ^2.1.1
  sliver_tools: ^0.2.10
  smooth_page_indicator: ^1.1.0
  stream_transform: ^2.1.0
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  wechat_assets_picker: ^8.4.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/chat/
    - assets/animation/

  fonts:
    - family: Kumbh_Sans
      fonts:
        - asset: assets/fonts/KumbhSans.ttf